// Invoices — generated by the studio, shown in the client portal, printable to
// PDF. Auto-numbered INV-YYYY-NNN. Stored in their own Neon table.
import { getSql } from "@/lib/db";

export type InvoiceItem = { label: string; amount: string };
export type InvoiceStatus = "draft" | "due" | "paid";

export type Invoice = {
  id: number;
  number: string;
  client_id: number;
  client_slug: string;
  issued_date: string;
  due_date: string | null;
  items: InvoiceItem[];
  note: string | null;
  status: InvoiceStatus;
  source: "custom" | "notion";
  vat_rate: number; // 0 = no VAT; otherwise percentage applied to the subtotal
  created_at: string;
};

export async function ensureInvoicesTable(): Promise<void> {
  const sql = getSql();
  await sql`
    CREATE TABLE IF NOT EXISTS invoices (
      id SERIAL PRIMARY KEY,
      number TEXT NOT NULL,
      client_id INTEGER NOT NULL,
      client_slug TEXT NOT NULL,
      issued_date DATE NOT NULL DEFAULT CURRENT_DATE,
      due_date DATE,
      items JSONB NOT NULL DEFAULT '[]'::jsonb,
      note TEXT,
      status TEXT NOT NULL DEFAULT 'draft',
      source TEXT NOT NULL DEFAULT 'custom',
      vat_rate NUMERIC NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `;
  await sql`ALTER TABLE invoices ADD COLUMN IF NOT EXISTS vat_rate NUMERIC NOT NULL DEFAULT 0`;
  // Status set was "draft | sent | paid"; "sent" is now "due".
  await sql`UPDATE invoices SET status = 'due' WHERE status = 'sent'`;
}

// INV-YYYY-NNN, sequential within the calendar year.
async function nextNumber(): Promise<string> {
  const sql = getSql();
  const year = new Date().getFullYear();
  const prefix = `INV-${year}-`;
  const rows = (await sql`
    SELECT number FROM invoices WHERE number LIKE ${prefix + "%"} ORDER BY id DESC LIMIT 1
  `) as unknown as { number: string }[];
  let n = 1;
  if (rows[0]) {
    const last = parseInt(rows[0].number.slice(prefix.length), 10);
    if (Number.isFinite(last)) n = last + 1;
  }
  return `${prefix}${String(n).padStart(3, "0")}`;
}

export async function createInvoice(input: {
  clientId: number;
  clientSlug: string;
  items: InvoiceItem[];
  note?: string;
  dueDate?: string;
  source?: "custom" | "notion";
  vatRate?: number;
}): Promise<{ id: number; number: string }> {
  await ensureInvoicesTable();
  const sql = getSql();
  const number = await nextNumber();
  const items = JSON.stringify(input.items || []);
  const vat = Number.isFinite(input.vatRate) ? Number(input.vatRate) : 0;
  const rows = (await sql`
    INSERT INTO invoices (number, client_id, client_slug, due_date, items, note, source, vat_rate)
    VALUES (${number}, ${input.clientId}, ${input.clientSlug}, ${input.dueDate || null}, ${items}::jsonb, ${input.note || null}, ${input.source || "custom"}, ${vat})
    RETURNING id
  `) as unknown as { id: number }[];
  return { id: rows[0].id, number };
}

export async function listInvoices(): Promise<Invoice[]> {
  const sql = getSql();
  return (await sql`
    SELECT id, number, client_id, client_slug, issued_date, due_date, items, note, status, source, vat_rate, created_at
    FROM invoices ORDER BY created_at DESC LIMIT 500
  `) as unknown as Invoice[];
}

export async function listClientInvoices(clientId: number): Promise<Invoice[]> {
  const sql = getSql();
  return (await sql`
    SELECT id, number, client_id, client_slug, issued_date, due_date, items, note, status, source, vat_rate, created_at
    FROM invoices WHERE client_id = ${clientId} ORDER BY created_at DESC
  `) as unknown as Invoice[];
}

export async function getInvoice(id: number): Promise<Invoice | undefined> {
  const sql = getSql();
  const rows = (await sql`
    SELECT id, number, client_id, client_slug, issued_date, due_date, items, note, status, source, vat_rate, created_at
    FROM invoices WHERE id = ${id} LIMIT 1
  `) as unknown as Invoice[];
  return rows[0];
}

export async function setInvoiceStatus(id: number, status: InvoiceStatus): Promise<void> {
  await getSql()`UPDATE invoices SET status = ${status} WHERE id = ${id}`;
}

export async function deleteInvoice(id: number): Promise<void> {
  await getSql()`DELETE FROM invoices WHERE id = ${id}`;
}

export function invoiceTotal(items: InvoiceItem[]): number {
  return (items || []).reduce((sum, it) => {
    const n = parseFloat((it.amount || "").replace(/[^0-9.]/g, ""));
    return sum + (Number.isFinite(n) ? n : 0);
  }, 0);
}

export function invoiceVat(items: InvoiceItem[], rate: number): number {
  return invoiceTotal(items) * (Number(rate) || 0) / 100;
}

export function invoiceGrandTotal(items: InvoiceItem[], rate: number): number {
  return invoiceTotal(items) + invoiceVat(items, rate);
}
