// Invoices — generated by the studio, shown in the client portal, printable to
// PDF. Auto-numbered INV-YYYY-NNN. Stored in their own Neon table.
import { getSql } from "@/lib/db";
import { readSnapshot, isOutageError } from "@/lib/snapshot";
import { APPROX_USD_ILS, amountLabelToIls as toIls } from "@/lib/money";
import { listClientPayments, ramziAmountOf } from "@/lib/payments";

export type InvoiceItem = { label: string; amount: string; kind?: LineKind; owner?: LineOwner };
export type InvoiceStatus = "draft" | "due" | "partial" | "paid";

// A line's category (drives the Notion Income row name so the budget formula
// classifies it) and who the money belongs to. "ramzi" lines are pass-through:
// they stay on the client's invoice but are never Marker income and never sync
// to Marker's Notion books. Stories collected on Ramzi's behalf are the case.
export type LineKind = "branding" | "plan" | "stories" | "extra";
export type LineOwner = "marker" | "ramzi";

// Parse the numeric part of a line amount ("1,800 ILS" → 1800). Single-currency
// per line; mixing happens across lines, not within one.
export function lineAmount(amount: string): number {
  const n = parseFloat((amount || "").replace(/[^0-9.]/g, ""));
  return Number.isFinite(n) ? n : 0;
}

// Stories / explicitly Ramzi-owned lines are collected for Ramzi, not Marker.
export function isRamziLine(it: InvoiceItem): boolean {
  return it.owner === "ramzi" || it.kind === "stories" || /stor(y|ies)/i.test(it.label || "");
}

// Best-effort category for a line: an explicit kind wins, otherwise guess from
// the label so legacy invoices still sync under the right Notion name.
export function inferKind(it: InvoiceItem): LineKind {
  if (it.kind) return it.kind;
  const l = (it.label || "").toLowerCase();
  if (/stor(y|ies)/.test(l)) return "stories";
  if (/brand/.test(l)) return "branding";
  if (/month|plan|social|marketing|cycle|retainer/.test(l)) return "plan";
  return "extra";
}

// The Notion Income row Name your budget formula expects per category.
export function notionNameForKind(kind: LineKind): string {
  return kind === "branding" ? "Branding" : kind === "plan" ? "Plan Payment" : kind === "stories" ? "Stories" : "Extra";
}

export type Invoice = {
  id: number;
  number: string;
  client_id: number;
  client_slug: string;
  issued_date: string;
  due_date: string | null;
  items: InvoiceItem[];
  note: string | null;
  status: InvoiceStatus;
  source: "custom" | "notion";
  vat_rate: number; // 0 = no VAT; otherwise percentage applied to the subtotal
  paid_amount: number; // already paid / deposit against this invoice
  archived_at: string | null; // hidden from the default admin list when set
  created_at: string;
};

export async function ensureInvoicesTable(): Promise<void> {
  const sql = getSql();
  await sql`
    CREATE TABLE IF NOT EXISTS invoices (
      id SERIAL PRIMARY KEY,
      number TEXT NOT NULL,
      client_id INTEGER NOT NULL,
      client_slug TEXT NOT NULL,
      issued_date DATE NOT NULL DEFAULT CURRENT_DATE,
      due_date DATE,
      items JSONB NOT NULL DEFAULT '[]'::jsonb,
      note TEXT,
      status TEXT NOT NULL DEFAULT 'draft',
      source TEXT NOT NULL DEFAULT 'custom',
      vat_rate NUMERIC NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
  `;
  await sql`ALTER TABLE invoices ADD COLUMN IF NOT EXISTS vat_rate NUMERIC NOT NULL DEFAULT 0`;
  await sql`ALTER TABLE invoices ADD COLUMN IF NOT EXISTS paid_amount NUMERIC NOT NULL DEFAULT 0`;
  await sql`ALTER TABLE invoices ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ`;
  // Status set was "draft | sent | paid"; "sent" is now "due".
  await sql`UPDATE invoices SET status = 'due' WHERE status = 'sent'`;
}

// INV-YYYY-NNN, sequential within the calendar year (the issue year, so a
// backdated payment gets a number from its own year's sequence).
async function nextNumber(year = new Date().getFullYear()): Promise<string> {
  const sql = getSql();
  const prefix = `INV-${year}-`;
  const rows = (await sql`
    SELECT number FROM invoices WHERE number LIKE ${prefix + "%"} ORDER BY id DESC LIMIT 1
  `) as unknown as { number: string }[];
  let n = 1;
  if (rows[0]) {
    const last = parseInt(rows[0].number.slice(prefix.length), 10);
    if (Number.isFinite(last)) n = last + 1;
  }
  return `${prefix}${String(n).padStart(3, "0")}`;
}

export async function createInvoice(input: {
  clientId: number;
  clientSlug: string;
  items: InvoiceItem[];
  note?: string;
  issuedDate?: string; // backdate historical payments so records keep their real timeline
  dueDate?: string;
  source?: "custom" | "notion";
  vatRate?: number;
  paidAmount?: number;
  status?: InvoiceStatus;
}): Promise<{ id: number; number: string }> {
  await ensureInvoicesTable();
  const sql = getSql();
  const items = JSON.stringify(input.items || []);
  const vat = Number.isFinite(input.vatRate) ? Number(input.vatRate) : 0;
  const paid = Number.isFinite(input.paidAmount) ? Math.max(0, Number(input.paidAmount)) : 0;
  const issued = input.issuedDate || new Date().toISOString().slice(0, 10);
  const issuedYear = parseInt(issued.slice(0, 4), 10);
  const number = await nextNumber(Number.isFinite(issuedYear) ? issuedYear : undefined);
  // Derive the opening status from what's been paid unless one was passed.
  const grand = invoiceGrandTotal(input.items || [], vat);
  const status = input.status || (paid <= 0 ? "draft" : paid >= grand && grand > 0 ? "paid" : "partial");
  const rows = (await sql`
    INSERT INTO invoices (number, client_id, client_slug, issued_date, due_date, items, note, source, vat_rate, paid_amount, status)
    VALUES (${number}, ${input.clientId}, ${input.clientSlug}, ${issued}, ${input.dueDate || null}, ${items}::jsonb, ${input.note || null}, ${input.source || "custom"}, ${vat}, ${paid}, ${status})
    RETURNING id
  `) as unknown as { id: number }[];
  return { id: rows[0].id, number };
}

export async function listInvoices(): Promise<Invoice[]> {
  const sql = getSql();
  try {
    return (await sql`
      SELECT id, number, client_id, client_slug, issued_date::text AS issued_date, due_date::text AS due_date, items, note, status, source, vat_rate, paid_amount, archived_at, created_at
      FROM invoices ORDER BY created_at DESC LIMIT 500
    `) as unknown as Invoice[];
  } catch (e) {
    // Database unreachable → serve the last studio snapshot (read-only mode).
    if (isOutageError(e)) {
      const snap = await readSnapshot();
      if (snap) return snap.invoices as Invoice[];
    }
    throw e;
  }
}

export async function listClientInvoices(clientId: number): Promise<Invoice[]> {
  const sql = getSql();
  try {
    return (await sql`
      SELECT id, number, client_id, client_slug, issued_date::text AS issued_date, due_date::text AS due_date, items, note, status, source, vat_rate, paid_amount, archived_at, created_at
      FROM invoices WHERE client_id = ${clientId} ORDER BY created_at DESC
    `) as unknown as Invoice[];
  } catch (e) {
    // Database unreachable → serve the last studio snapshot (read-only mode)
    // so the client portal's invoices stay visible through an outage.
    if (isOutageError(e)) {
      const snap = await readSnapshot();
      if (snap) return (snap.invoices as Invoice[]).filter((i) => i.client_id === clientId);
    }
    throw e;
  }
}

// Combined client finance from the app's REAL invoices — every line: marketing,
// branding AND stories — in ILS (USD invoices converted at the steady rate).
// This is the client-facing truth. Notion holds only Marker's marketing/branding
// books (stories are dropped on sync), so the portal must combine here instead:
// a 1,800 invoice split 1,000 stories / 800 marketing reads as 1,800 owed, never
// the Marker-only 800. Draft and archived invoices are excluded.
export async function clientInvoiceFinanceIls(
  clientId: number
): Promise<{ totalIls: number; paidIls: number; openIls: number; count: number }> {
  let invs: Invoice[] = [];
  try {
    invs = await listClientInvoices(clientId);
  } catch {
    return { totalIls: 0, paidIls: 0, openIls: 0, count: 0 };
  }
  let totalIls = 0;
  let paidIls = 0;
  let count = 0;
  for (const inv of invs) {
    if (inv.archived_at || inv.status === "draft") continue;
    // Sum each line in ILS (amountLabelToIls reads "$"/"ILS" per line, so a
    // mixed-currency invoice is never multiplied by a single blanket rate), then
    // apply VAT. The paid amount is a single figure in the invoice's currency.
    const items = inv.items || [];
    const itemsIls = items.reduce((s, it) => s + toIls(it.amount || ""), 0);
    const grandIls = itemsIls * (1 + (Number(inv.vat_rate) || 0) / 100);
    const paidRate = invoiceCurrency(items) === "USD" ? APPROX_USD_ILS : 1;
    totalIls += grandIls;
    paidIls += (Number(inv.paid_amount) || 0) * paidRate;
    count++;
  }
  totalIls = Math.round(totalIls);
  paidIls = Math.round(paidIls);
  return { totalIls, paidIls, openIls: Math.max(0, totalIls - paidIls), count };
}

// The STORIES side of a client's money, in ILS — the part Notion never sees
// (stories are dropped on sync, collected for Ramzi). Billed = stories lines on
// the client's real invoices; collected = the stories portion of every recorded
// payment. The open figure is what's layered on top of Notion's Marker-only
// balance so the client's portal shows the true combined "money left".
export async function clientStoriesFinanceIls(
  clientId: number,
  clientSlug: string
): Promise<{ billedIls: number; collectedIls: number; openIls: number }> {
  let invs: Invoice[] = [];
  try {
    invs = await listClientInvoices(clientId);
  } catch {
    invs = [];
  }
  let billedIls = 0;
  for (const inv of invs) {
    if (inv.archived_at || inv.status === "draft") continue;
    // Stories lines summed in ILS per line (handles a USD stories line on an
    // otherwise-ILS invoice, and vice-versa).
    billedIls += (inv.items || []).filter(isRamziLine).reduce((s, it) => s + toIls(it.amount || ""), 0);
  }
  let collectedIls = 0;
  try {
    for (const p of await listClientPayments(clientSlug)) {
      const rate = p.currency === "USD" ? APPROX_USD_ILS : 1;
      collectedIls += ramziAmountOf(p) * rate;
    }
  } catch {
    /* no payments / table — collected stays 0 */
  }
  billedIls = Math.round(billedIls);
  collectedIls = Math.round(collectedIls);
  return { billedIls, collectedIls, openIls: Math.max(0, billedIls - collectedIls) };
}

export async function getInvoice(id: number): Promise<Invoice | undefined> {
  const sql = getSql();
  const rows = (await sql`
    SELECT id, number, client_id, client_slug, issued_date::text AS issued_date, due_date::text AS due_date, items, note, status, source, vat_rate, paid_amount, archived_at, created_at
    FROM invoices WHERE id = ${id} LIMIT 1
  `) as unknown as Invoice[];
  return rows[0];
}

// Archive hides an invoice from the default admin list (kept for records).
export async function setInvoiceArchived(id: number, archived: boolean): Promise<void> {
  if (archived) {
    await getSql()`UPDATE invoices SET archived_at = now() WHERE id = ${id}`;
  } else {
    await getSql()`UPDATE invoices SET archived_at = NULL WHERE id = ${id}`;
  }
}

export async function setInvoiceStatus(id: number, status: InvoiceStatus): Promise<void> {
  await getSql()`UPDATE invoices SET status = ${status} WHERE id = ${id}`;
}

// Edit an existing invoice's lines / VAT / due date / note. Keeps whatever has
// already been paid and re-derives the status from the new total, so changing
// amounts can't leave a "paid" invoice that no longer adds up. Past Notion
// payments are not rewritten — only future payments sync against the new lines.
export async function updateInvoice(
  id: number,
  input: { items: InvoiceItem[]; note?: string; dueDate?: string | null; vatRate?: number }
): Promise<void> {
  const sql = getSql();
  const cur = await getInvoice(id);
  if (!cur) return;
  const items = input.items || [];
  const vat = Number.isFinite(input.vatRate) ? Number(input.vatRate) : 0;
  const paid = Number(cur.paid_amount) || 0;
  const grand = invoiceGrandTotal(items, vat);
  const status: InvoiceStatus =
    paid <= 0 ? (cur.status === "draft" ? "draft" : "due") : paid >= grand && grand > 0 ? "paid" : "partial";
  await sql`
    UPDATE invoices
    SET items = ${JSON.stringify(items)}::jsonb, note = ${input.note || null},
        due_date = ${input.dueDate || null}, vat_rate = ${vat}, status = ${status}
    WHERE id = ${id}
  `;
}

export async function deleteInvoice(id: number): Promise<void> {
  await getSql()`DELETE FROM invoices WHERE id = ${id}`;
}

export function invoiceTotal(items: InvoiceItem[]): number {
  return (items || []).reduce((sum, it) => sum + lineAmount(it.amount), 0);
}

// Subtotal of just Marker's lines (excludes Ramzi pass-through) and just
// Ramzi's lines — for splitting one invoice's money between the two books.
export function markerItemsTotal(items: InvoiceItem[]): number {
  return (items || []).filter((it) => !isRamziLine(it)).reduce((s, it) => s + lineAmount(it.amount), 0);
}
export function ramziItemsTotal(items: InvoiceItem[]): number {
  return (items || []).filter(isRamziLine).reduce((s, it) => s + lineAmount(it.amount), 0);
}

// Guess an invoice's currency from its line amounts — "$"/"USD" → USD, else ILS
// (the studio's default). Used when mirroring a payment back to Notion's Income
// database, which has separate ILS and USD number columns.
export function invoiceCurrency(items: InvoiceItem[]): "ILS" | "USD" {
  const joined = (items || []).map((i) => i.amount || "").join(" ");
  return /\$|usd/i.test(joined) ? "USD" : "ILS";
}

// Re-exported from the dependency-free money module (kept here so existing
// server-side imports `from "@/lib/invoices"` keep working).
export { amountLabelToIls } from "@/lib/money";

export function invoiceVat(items: InvoiceItem[], rate: number): number {
  return invoiceTotal(items) * (Number(rate) || 0) / 100;
}

export function invoiceGrandTotal(items: InvoiceItem[], rate: number): number {
  return invoiceTotal(items) + invoiceVat(items, rate);
}

// "Money left" — what's still owed after any deposit / partial payment.
export function invoiceRemaining(items: InvoiceItem[], rate: number, paid: number): number {
  return Math.max(0, invoiceGrandTotal(items, rate) - (Number(paid) || 0));
}

// Add a paid amount and re-derive the status (draft → partial → paid).
export async function setInvoicePaid(id: number, paid: number): Promise<void> {
  const sql = getSql();
  const rows = (await sql`SELECT items, vat_rate FROM invoices WHERE id = ${id} LIMIT 1`) as unknown as { items: InvoiceItem[]; vat_rate: number }[];
  if (!rows[0]) return;
  const grand = invoiceGrandTotal(rows[0].items, Number(rows[0].vat_rate) || 0);
  const p = Math.max(0, Number(paid) || 0);
  const status: InvoiceStatus = p <= 0 ? "due" : p >= grand && grand > 0 ? "paid" : "partial";
  await sql`UPDATE invoices SET paid_amount = ${p}, status = ${status} WHERE id = ${id}`;
}
